#!/bin/bash -eu

relpath(){ python -c "import os.path; print(os.path.relpath('$1','${2:-$PWD}'))"; }
# -- http://stackoverflow.com/questions/2564634/bash-convert-absolute-path-into-relative-path-given-a-current-directory

srcdir="$(dirname $0)"/home
targetdir=~
srcdir_rel="./$(relpath $srcdir $targetdir)"

cd $targetdir

while read -r -d '' linkfile; do
  basename="$(basename "$linkfile")"
  targetpath="$HOME/${basename%.*}"
  if [[ ! -f "$targetpath" ]]; then
    echo "$targetpath is not a regular file"
  fi
  if [[ -f "$targetpath" && ! -L "$targetpath" ]]; then
    cp "$targetpath" "$linkfile"
    ln -sf "$linkfile" "$targetpath"
  fi
done < <(find "$srcdir_rel" -name \*.symlink -print0)
