#!/bin/bash -eu

relpath(){ python -c "import os.path; print os.path.relpath('$1','${2:-$PWD}')" ; }
# -- http://stackoverflow.com/questions/2564634/bash-convert-absolute-path-into-relative-path-given-a-current-directory

srcdir="$(dirname $0)"
targetdir=~
srcdir_rel="./$(relpath $srcdir $targetdir)"

cd $targetdir

while read -r -d '' file; do
  basename="$(basename "$file")"
  targetpath="${basename%.*}"
  ln -sf "$file" "$targetpath"
done < <(find "$srcdir_rel" -name \*.symlink -print0)
