#!/bin/bash -eu

relpath(){ python -c "import os.path; print(os.path.relpath('$1','${2:-$PWD}'))"; }
# -- http://stackoverflow.com/questions/2564634/bash-convert-absolute-path-into-relative-path-given-a-current-directory

srcdir="$(dirname $0)"/../home
targetdir=~
srcdir_rel="./$(relpath $srcdir $targetdir)"

cd $targetdir

while read -r -d '' repo_file; do
  basename="$(basename "$repo_file")"
  dotfile="${basename%.*}"
  if [[ ! -f "$dotfile" ]]; then
    echo "$dotfile is not a regular file"
  fi
  if [[ -f "$dotfile" && ! -L "$dotfile" ]]; then
    cp "$dotfile" "$repo_file"
    ln -sf "$repo_file" "$dotfile"
  fi
done < <(find "$srcdir_rel" -name \*.symlink -print0)
