#!/bin/bash -eu

# Shows home directory dotfiles that don't link that files in this repo.

relpath(){ python -c "import os.path; print(os.path.relpath('$1','${2:-$PWD}'))"; }
# -- http://stackoverflow.com/questions/2564634/bash-convert-absolute-path-into-relative-path-given-a-current-directory

srcdir="$(dirname $0)"/../home
targetdir=~
srcdir_rel="./$(relpath $srcdir $targetdir)"

cd $targetdir

for dotfile in .*; do
  if [[ "$dotfile" =~ .*_history || "$dotfile" == '.DS_Store' ]]; then
    true  # ignore whitelisted files
  elif [[ -d "$dotfile" ]]; then
    true  # ignore directories
  elif [[ -L "$dotfile" ]]; then
    link_target=$(readlink -n "$dotfile")
    repo_file="$srcdir_rel/${dotfile}"
    if [[ "$link_target" != "$repo_file" ]]; then
      echo "$dotfile: symlink -> $link_target"
    fi
  elif [[ ! -f "$dotfile" ]]; then
    echo "$dotfile: not a regular file"
  else
    file "$dotfile"
  fi
done < <(find "$srcdir_rel" -name \* -print0)
