#!/bin/bash -eu

relpath(){ python -c "import os.path; print(os.path.relpath('$1','${2:-$PWD}'))"; }
# -- http://stackoverflow.com/questions/2564634/bash-convert-absolute-path-into-relative-path-given-a-current-directory

srcdir="$(dirname $0)"/../home
targetdir=~
srcdir_rel="./$(relpath $srcdir $targetdir)"

cd $targetdir

for dotfile in .*; do
  if [[ "$dotfile" == '.' || "$dotfile" == '..' ]]; then
    true  # ignore
  elif [[ -d "$dotfile" ]]; then
    true  # ignore directories
  elif [[ ! -f "$dotfile" ]]; then
    echo "$dotfile is not a regular file"
  elif [[ -L "$dotfile" ]]; then
    link_target=$(readlink -n "$dotfile")
    repo_file="$srcdir_rel/${dotfile}.symlink"
    if [[ "$link_target" != "$repo_file" ]]; then
      echo "$dotfile is a symbolic link to $link_target"
      echo "actual  : $link_target"
      echo "expected: $repo_file"
    fi
  else
    echo "$dotfile"
  fi
done < <(find "$srcdir_rel" -name \*.symlink -print0)
