#!/bin/bash -eu

# Symlink dotfiles in this repo into the user's home directory.
# This overwrites files that were already there.

relpath(){ python -c "import os.path; print(os.path.relpath('$1','${2:-$PWD}'))"; }
# -- http://stackoverflow.com/questions/2564634/bash-convert-absolute-path-into-relative-path-given-a-current-directory

srcdir="$(dirname $0)"/../home
targetdir=~
srcdir_rel="./$(relpath $srcdir $targetdir)"

cd "$targetdir"

# DRY_RUN_PREFIX=echo

while read -r -d '' link_target; do
  basename="$(basename "$link_target")"
  ${DRY_RUN_PREFIX:-} ln -sf "$link_target" "$basename"
done < <(find "$srcdir_rel" -name \* -print0)
