#!/usr/bin/env python3
import subprocess
import sys
import json
from pathlib import Path


def shellexec(*cmd):
    result = subprocess.run(cmd, capture_output=True, text=True)
    result.check_returncode()
    return result.stdout.rstrip()


deps = json.load(Path("package.json").open())["dependencies"]

npm_root_dir = shellexec("npm", "root", "-g")
installed = {
    p.name: shellexec("jq", ".version", json_path)
    for p in [p for p in Path(npm_root_dir).iterdir()]
    for json_path in [p / "package.json"]
    if json_path.is_file()
}

for package in deps - installed.keys():
    print(f"Installing {package}...")
    shellexec("npm", "install", "-g", package)
