#!/bin/bash -eu

smudgable_files () {
  for glob in $(awk '/filter=/ {print $1}' .gitattributes); do
    find . -name "$glob" -type f
  done
}

files=$(smudgable_files)
rm -f "$@"
git checkout HEAD -- "$@"
