#!/usr/bin/env ruby

# TODO DRY /w clean_secrets_filter
SECRETS_PATH = File.join(`git rev-parse --show-toplevel`.chomp, ".git/info/secrets")
secrets = Hash[File.open(SECRETS_PATH, "r").read.scan(/(\w+)\s*[=:]\s*(\S+)/)]
matcher = /(#{secrets.keys.map {|k| Regexp.quote k}.join('|')})/

ARGF.each do |line|
    if line =~ matcher
      name = $1
      secret = secrets[name]
      puts line.gsub(/\$secret\(#{name}\)/, secret)
      STDERR.puts "smudged #{name}" if ENV['DEBUG_GIT_FILTERS']
    elsif line =~ /\$secret\(\S+?\)/
      STDERR.puts "Warning: #{$1} not smudged"
    else
      puts line
    end
end
