#!/usr/bin/env ruby

def die(msg)
  STDERR.puts msg
  exit 1
end

# TODO DRY /w clean_secrets_filter
SECRETS_PATH = `git config filter.secrets.file`.chomp
die "git config filter.secrets.file not set; skipping filter" if SECRETS_PATH.empty?
die "File #{SECRETS_PATH} not found; skipping filter" unless File.exists? SECRETS_PATH

secrets = Hash[File.open(SECRETS_PATH, "r").read.scan(/(\w+)\s*[=:]\s*(\S+)/)]
matcher = /(#{secrets.keys.map {|k| Regexp.quote k}.join('|')})/

ARGF.each do |line|
    if line =~ matcher
      name = $1
      secret = secrets[name]
      puts line.gsub(/\$secret\(#{name}\)/, secret)
      STDERR.puts "smudged #{name}" if ENV['DEBUG_GIT_FILTERS']
    elsif line =~ /\$secret\(\S+?\)/
      STDERR.puts "Warning: #{$1} not smudged"
    else
      puts line
    end
end
